name: Check for missing XML elements

on: 
  pull_request:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        # Install XPath library
        npm install xpath xmldom
        
  check-xml-elements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for missing XML elements
      run: |
        # Install XPath library
        npm install xpath
        
        # Iterate over all XML files in the repository
        for file in $(find . -name "*.xml"); do
          # Parse XML file using XPath library
          node -e "const xpath = require('xpath'); const dom = require('xpath/lib/dom'); const fs = require('fs'); const xml = fs.readFileSync('$file', 'utf8'); const doc = new dom.DOMParser().parseFromString(xml); const nodes = xpath.select('//help | //description', doc); for (const node of nodes) { if (!node.firstChild || !node.firstChild.data.trim()) console.log('Empty element found in file $file'); }"
        done
        
        # Check if any empty elements were found
        if [[ -n $(cat error.log) ]]; then
          # Use GitHub REST API to create a comment on the relevant pull request
          curl -H "Authorization: Bearer $GITHUB_TOKEN" -X POST -d '{"body":"Empty `<help/>` or `<description/>` element found in one or more XML files. Please add content to these elements."}' https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PULL_REQUEST_NUMBER/comments
        fi

